# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T3b2mEl67G5i9sgFx7djLh29M5zdhppQ
"""

def suma(a, b):
    return a + b